-- 1번 : 모델링 구현
--   TBL_MEMBER
--   MEMBER_NUMBER   NUMBER      PK
--   MEMBER_NAME   VARCHAR2(30)   NOT NULL
--   MEMBER_AGE   NUMBER      
--   MEMBER_PHONE   VARCHAR2(20)   UNIQUE, NOT NULL
--   MEMBER_ADDRESS   VARCHAR2(100)   NOT NULL
SELECT * FROM TBL_MEMBER;
DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_MEMBER(
   MEMBER_NUMBER NUMBER,
   MEMBER_NAME VARCHAR2(30) NOT NULL,
   MEMBER_AGE NUMBER,
   MEMBER_PHONE VARCHAR2(20) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(100) NOT NULL,
   CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NUMBER),
   CONSTRAINT UK_MEMBER UNIQUE(MEMBER_PHONE) 
);

SELECT * FROM TBL_MEMBER;
--   TBL_BOOK
--   BOOK_NUMBER   NUMBER      PK
--   BOOK_TITLE   VARCHAR2(100)   NOT NULL
--   BOOK_GENRE    VARCHAR2(20)   CHECK   IN(인문학, 추리, IT, 로맨스)
--   MEMBER_NUMBER   NUMBER      FK

CREATE TABLE TBL_BOOK(
   BOOK_NUMBER NUMBER,
   BOOK_TITLE VARCHAR2(100) NOT NULL,
   BOOK_GENRE VARCHAR2(20),
   MEMBER_NUMBER NUMBER,
   CONSTRAINT PK_BOOK PRIMARY KEY(BOOK_NUMBER),
   CONSTRAINT CHK_GENRE CHECK (BOOK_GENRE IN ('인문학', '추리', 'IT', '로맨스')),
   CONSTRAINT FK_MEMBER_BOOK FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER)
);

SELECT * FROM TBL_BOOK;