-- 학교테이블(부모테이블) / 학생테이블(자식테이블)
CREATE TABLE TBL_SCHOOL( 
   SCHOOL_NUMBER NUMBER,
   SCHOOL_NAME VARCHAR2(100),
   CONSTRAINT PK_SCHOOL PRIMARY KEY(SCHOOL_NUMBER)
);

--DROP TABLE TBL_STUDENT;
CREATE TABLE TBL_STUDENT(
   STUDENT_NUMBER NUMBER,
   STUDENT_NAME VARCHAR2(100),
   STUDENT_AGE NUMBER,
   SCHOOL_NUMBER NUMBER,
   CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NUMBER),
   CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY(SCHOOL_NUMBER) REFERENCES TBL_SCHOOL(SCHOOL_NUMBER)
);

SELECT * FROM TBL_STUDENT;
SELECT * FROM TBL_SCHOOL;

INSERT INTO TBL_SCHOOL 
--VALUES(1, 'JAVA 고등학교');
--VALUES(2, 'DBMS 고등학교');
--VALUES(3, 'KOREA 고등학교');
--VALUES(4, '한국 고등학교');



INSERT INTO TBL_STUDENT
--VALUES(1, '짱구', 17, 1);
--VALUES(2, '철수', 19, 2);
--VALUES(3, '유리', 17, 1);
--VALUES(4, '맹구', 17, NULL);
--VALUES(5, '훈이', 19, 5); -- 오류발생 FK인 SCHOOL_NUMBER에 존재하지 않는 값을 저장하려하면 오류발생
--VALUES(5, '훈이', 19, 3);
--VALUES(6, '치타', 18, 2);

SELECT * FROM TBL_STUDENT;

