-- 도서관
-- 도서, 회원, 렌탈
CREATE TABLE TBL_BOOKS( 
   BOOKS_ID NUMBER,
   BOOKS_TITLE VARCHAR2(100),
   BOOKS_AUTHOR VARCHAR2(100),
   CONSTRAINT BOOKS_PK PRIMARY KEY(BOOKS_ID)
);

CREATE TABLE TBL_MEMBERS(
   MEM_ID NUMBER,
   MEM_NAME VARCHAR2(100),
   MEM_PHONE VARCHAR2(100),
   MEM_EMAIL VARCHAR2(100),
   CONSTRAINT MEMBERS_PK PRIMARY KEY(MEM_ID)
);

CREATE TABLE TBL_RENTAL(
   REN_ID NUMBER,
   MEM_ID NUMBER,
   BOOKS_ID NUMBER,
   REN_RENTAL_DATE DATE,
   REN_RETURN_DATE DATE,
   CONSTRAINT RENTAL_PK PRIMARY KEY(REN_ID),
   CONSTRAINT RENTAL_BOOKS_FK FOREIGN KEY(BOOKS_ID) REFERENCES TBL_BOOKS(BOOKS_ID),
   CONSTRAINT RENTAL_MEMBERS_FK FOREIGN KEY(MEM_ID) REFERENCES TBL_MEMBERS(MEM_ID)
);

SELECT * FROM TBL_RENTAL;
SELECT * FROM TBL_BOOKS;
SELECT * FROM TBL_MEMBERS;

INSERT ALL 	
	INTO TBL_BOOKS VALUES(1, '위대한 개츠비', 'F.스콧 피츠제럴드')
	INTO TBL_BOOKS VALUES(2, '해리포터와 마법사의 돌', 'J.K. 롤링')
	INTO TBL_BOOKS VALUES(3, '1984', '조지오웰')
	INTO TBL_BOOKS VALUES(4, '오만과 편견', '제인 오스틴')
	INTO TBL_BOOKS VALUES(5, '데미안', '헤르만 헤세')
SELECT 1 FROM dual;

INSERT INTO TBL_MEMBERS
--VALUES
--VALUES(1, '짱구', '123-456-7890', 'aaa@koreait.com');
--VALUES(2, '유리', '987-654-3210', 'bbb@koreait.com');
--VALUES(3, '철수', '555-123-4567', 'ccc@koreait.com');
--(4, '훈이', '777-888-9999', 'ddd@koreait.com');
--(5, '맹구', '555-777-3333', 'eee@koreait.com');

INSERT ALL
	INTO TBL_RENTAL VALUES (1, 1, 3, TO_DATE('2023-12-11', 'YYYY-MM-DD'), TO_DATE('2023-12-18', 'YYYY-MM-DD'))
	INTO TBL_RENTAL VALUES (2, 2, 1, TO_DATE('2023-12-11', 'YYYY-MM-DD'), TO_DATE('2023-12-18', 'YYYY-MM-DD'))
	INTO TBL_RENTAL VALUES (3, 3, 2, TO_DATE('2023-12-13', 'YYYY-MM-DD'), TO_DATE('2023-12-20', 'YYYY-MM-DD'))
	INTO TBL_RENTAL VALUES (4, 4, 4, TO_DATE('2023-12-20', 'YYYY-MM-DD'), TO_DATE('2023-12-27', 'YYYY-MM-DD'))
	INTO TBL_RENTAL VALUES (5, 5, 5, TO_DATE('2023-12-22', 'YYYY-MM-DD'), TO_DATE('2023-12-29', 'YYYY-MM-DD'))
SELECT 1 FROM dual;

SELECT * FROM TBL_RENTAL;
SELECT * FROM TBL_BOOKS;
SELECT * FROM TBL_MEMBERS;
